apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop-frontend-v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eshop-frontend
  template:
    metadata:
      labels:
        app: eshop-frontend
        version: v1
    spec:
      containers:
        - name: eshop-frontend
          image: gcr.io/architect-certification-289902/23/eshop-frontend:1
          ports:
          - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop-frontend-v2
spec:
  selector:
    matchLabels:
      app: eshop-frontend
  template:
    metadata:
      labels:
        app: eshop-frontend
        version: v2
    spec:
      containers:
        - name: eshop-frontend
          image: gcr.io/architect-certification-289902/23/eshop-frontend:3
          ports:
          - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: eshop-frontend
spec:
  type: ClusterIP
  selector:
    app: eshop-frontend
  ports:
  - port: 8080